### ISSUE TITLE
Options支不支持Secrets?

### ISSUE THREAD

**Issue by Kopei** [AliyunContainerService/flexvolume#4]
支不支持如下写法？不想在yml中写密钥信息。[https://help.aliyun.com/document_detail/63957.html](https://help.aliyun.com/document_detail/63957.html)
```
 flexVolume:
    driver: "alicloud/oss"
    options:
      bucket: "docker"
      url: "oss-cn-hangzhou.aliyuncs.com"
      akId: 
           secretKeyRef:
                name: secrets_key
                key: password1
      akSecret: 
           secretKeyRef:
                name: secrets_ak
                key: password2
```
